// GENERATED by scripts/create-pack.ts --index: the handler map, by operationId, from the families' files (each
// handler named as its operation). Do not edit; add a handler to its family's file and generate again.
import type { Handler } from '@volter/world-core';
import * as extract from './extract.ts';
import * as search from './search.ts';

export const tavilySemantics: Record<string, Handler> = {
  extract: extract.extract,
  search: search.search,
};
